---
# This is the master playbook.

- name: configuration common to all hosts
  hosts: all
  become: yes

  roles:
    - common
    - users
    - { role: databases, tags: [ 'databases' ] }
    - { role: nginx, tags: [ 'nginx' ] }

  vars_files:
    - vars/main.yml
