---
- name: Create admin group
  group:
    name: "{{ admin_group }}"
    gid: "{{ admin_gid }}"
    state: present

- name: Create admin user
  user:
    name: "{{ admin }}"
    uid: "{{ admin_uid }}"
    groups: "{{ admin_group }},sudo,dialout"
    home: "{{ admin_home }}"
    createhome: yes
    shell: /bin/bash
    password: "{{ admin_password }}"
    state: present
