---
# Common apt tasks

- name: install basic packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - debconf-utils
    - build-essential
    - checkinstall
    - git
    - curl
    - wget
